title: 楽天モバイルで節約生活
description: 楽天社員がおすすめする楽天モバイルの活用法・乗り換え情報・節約術
url: "https://mobile-friend.com"
lang: ja
timezone: Asia/Tokyo

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      lang: ja
